import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner/Banner";
import Card from "../components/card/Card";
import SectionCard from "../components/card/Section-card";
import Nav from "../components/nav/Nav";
import styles from "../styles/Home.module.css";
import { getPopularVideos, getSyncVideos, getVideos } from "../lib/videos";
import { magic } from "../lib/magic-client";
import { getWatchedVideos } from "../db/Hasura";
import { getUserIdFromToken } from "../lib/utils";
import UseExtractToken from "../utils/useExtractToken";

export async function getServerSideProps(context) {
  const { userId, token } = UseExtractToken(context);

  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  // const disneyVideos = await getVideos("disney trailure");
  // const travelVideos = await getVideos("travel");
  // const productivityVideos = await getVideos("productivity");
  // const popularVideos = await getPopularVideos();
  const disneyVideos = await getVideos("disney trailure");
  const travelVideos = await getVideos("travel");
  const productivityVideos = await getVideos("productivity");
  const popularVideos = await getPopularVideos();
  const fetchWatchedVideos = await getWatchedVideos(userId, token);
  const watchedVideos = fetchWatchedVideos.map((video) => ({
    id: video.videoId,
    imgUrl: `https://i.ytimg.com/vi/${video.videoId}/maxresdefault.jpg`,
  }));
  console.log(fetchWatchedVideos, "getWatchedVideos");
  return {
    props: {
      disneyVideos,
      travelVideos,
      productivityVideos,
      popularVideos,
      watchedVideos,
    },
  };
}

export default function Home({
  disneyVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
  watchedVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav username={"ammad10e3@sd.dss"} />
      <Banner
        title="Clifford the Big Red Dog"
        subtitle="a very cute dog"
        imgUrl="/static/clifford.webp"
        videoId="togmdDHG3Pw"
      />
      <div className={styles.sectionWrapper}>
        <SectionCard title="Disney" videos={disneyVideos} size="large" />
        <SectionCard title="Watch Again" videos={watchedVideos} size="small" />
        <SectionCard title="Travel" videos={travelVideos} size="small" />
        <SectionCard
          title="Productivity"
          videos={productivityVideos}
          size="medium"
        />
        <SectionCard title="Popular" videos={popularVideos} size="small" />
      </div>
    </div>
  );
}
